version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/liquidity_backend:latest
    container_name: liquidity_backend
    network_mode: host
    env_file:
      - .env
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/liquidity_frontend:latest
    container_name: liquidity_frontend
    network_mode: host
    depends_on:
      - backend
    restart: always
